INSERT INTO USERS (USERNAME, PASSWORD, EMAIL, ROLE) VALUES ('admin', 'admin','admin@gmail.com', 'ADMIN');
INSERT INTO USERS (USERNAME, EMAIL, PASSWORD, ROLE) VALUES ('user', 'use@gmail.com', 'user', 'USER');


INSERT INTO CATEGORIES (NAME) VALUES ('pizza');
INSERT INTO CATEGORIES (NAME) VALUES ('leves');
INSERT INTO ITEMS (DESCRIPTION, IS_SPICY, IS_VEGETARIAN, NAME, PRICE,CATEGORY_ID) VALUES ('user desc', 'true', 'true', 'Hawaii Pizza','1543' ,1);
INSERT INTO ITEMS (IS_SPICY, IS_VEGETARIAN, NAME, PRICE,CATEGORY_ID) VALUES ('true', 'true', 'Water','13' ,2);

INSERT INTO ORDERS (NAME, ADDRESS, PHONE, RECEIVED,STATUS,USER_ID) VALUES ('James', 'Water str 12.', '887762',current_timestamp,'IDLE',2);
INSERT INTO ORDERS (NAME, ADDRESS, PHONE, RECEIVED,DELIVERED,STATUS,USER_ID) VALUES ('James', 'Water str 12.', '887762',current_timestamp,current_timestamp,'DELIVERED',1);

INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID) VALUES (1,1);
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID) VALUES (1,2);
INSERT INTO ORDER_ITEMS (ORDER_ID, ITEM_ID) VALUES (2,2);